In [ ]:
# grouping data by category
# why group data: to perform analysis on data and get insights of data

# groupby in pandas
# groupby is a function that groups data by a column

In [5]:
import pandas as pd
df=pd.read_csv("iris.csv")
print(df)

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
grouped=df.groupby("species")
print(grouped)
grouped.mean()

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000001CF20DF3390>

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.428         1.462        0.246
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [ ]:
# operations
# 1.iterate over groups
# 2.apply aggregate functions

In [12]:
for name, group in grouped:
    print("Group name:", name)
    print("Group:", group)

Group name: setosa
Group:     sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
22           4.6          3.6           1.0          0.2  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa
30           4.8          3.1           1.6          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa
32           5.2          4.1           1.5          0.1  setosa
33           5.5          4.2           1.4          0.2  setosa
34           4.9          3.1           1.5          0.2  setosa
35           5.0          3.2           1.2          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa
37           4.9          3.6           1.4          0.1  setosa
38           4.4          3.0           1.3          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
40           5.0          3.5           1.3          0.3  setosa
41           4.5          2.3           1.3          0.3  setosa
42           4.4          3.2           1.3          0.2  setosa
43           5.0          3.5           1.6          0.6  setosa
44           5.1          3.8           1.9          0.4  setosa
45           4.8          3.0           1.4          0.3  setosa
46           5.1          3.8           1.6          0.2  setosa
47           4.6          3.2           1.4          0.2  setosa
48           5.3          3.7           1.5          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa
Group name: versicolor
Group:     sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor
51           6.4          3.2           4.5          1.5  versicolor
52           6.9          3.1           4.9          1.5  versicolor
53           5.5          2.3           4.0          1.3  versicolor
54           6.5          2.8           4.6          1.5  versicolor
55           5.7          2.8           4.5          1.3  versicolor
56           6.3          3.3           4.7          1.6  versicolor
57           4.9          2.4           3.3          1.0  versicolor
58           6.6          2.9           4.6          1.3  versicolor
59           5.2          2.7           3.9          1.4  versicolor
60           5.0          2.0           3.5          1.0  versicolor
61           5.9          3.0           4.2          1.5  versicolor
62           6.0          2.2           4.0          1.0  versicolor
63           6.1          2.9           4.7          1.4  versicolor
64           5.6          2.9           3.6          1.3  versicolor
65           6.7          3.1           4.4          1.4  versicolor
66           5.6          3.0           4.5          1.5  versicolor
67           5.8          2.7           4.1          1.0  versicolor
68           6.2          2.2           4.5          1.5  versicolor
69           5.6          2.5           3.9          1.1  versicolor
70           5.9          3.2           4.8          1.8  versicolor
71           6.1          2.8           4.0          1.3  versicolor
72           6.3          2.5           4.9          1.5  versicolor
73           6.1          2.8           4.7          1.2  versicolor
74           6.4          2.9           4.3          1.3  versicolor
75           6.6          3.0           4.4          1.4  versicolor
76           6.8          2.8           4.8          1.4  versicolor
77           6.7          3.0           5.0          1.7  versicolor
78           6.0          2.9           4.5          1.5  versicolor
79           5.7          2.6           3.5          1.0  versicolor
80           5.5          2.4           3.8          1.1  versicolor
81           5.5          2.4           3.7          1.0  versicolor
82           5.8          2.7           3.9          1.2  versicolor
83           6.0          2.7           5.1          1.6  versicolor
84           5.4          3.0           4.5          1.5  versicolor
85           6.0          3.4           4.5          1.6  versicolor
86           6.7          3.1           4.7          1.5  versicolor
87           6.3          2.3           4.4          1.3  versicolor
88           5.6          3.0           4.1          1.3  versicolor
89           5.5          2.5           4.0          1.3  versicolor
90           5.5          2.6           4.4          1.2  versicolor
91           6.1          3.0           4.6          1.4  versicolor
92           5.8          2.6           4.0          1.2  versicolor
93           5.0          2.3           3.3          1.0  versicolor
94           5.6          2.7           4.2          1.3  versicolor
95           5.7          3.0           4.2          1.2  versicolor
96           5.7          2.9           4.2          1.3  versicolor
97           6.2          2.9           4.3          1.3  versicolor
98           5.1          2.5           3.0          1.1  versicolor
99           5.7          2.8           4.1          1.3  versicolor
Group name: virginica
Group:      sepal_length  sepal_width  petal_length  petal_width    species
100           6.3          3.3           6.0          2.5  virginica
101           5.8          2.7           5.1          1.9  virginica
102           7.1          3.0           5.9          2.1  virginica
103           6.3          2.9           5.6          1.8  virginica
104           6.5          3.0           5.8          2.2  virginica
105           7.6          3.0           6.6          2.1  virginica
106           4.9          2.5           4.5          1.7  virginica
107           7.3          2.9           6.3          1.8  virginica
108           6.7          2.5           5.8          1.8  virginica
109           7.2          3.6           6.1          2.5  virginica
110           6.5          3.2           5.1          2.0  virginica
111           6.4          2.7           5.3          1.9  virginica
112           6.8          3.0           5.5          2.1  virginica
113           5.7          2.5           5.0          2.0  virginica
114           5.8          2.8           5.1          2.4  virginica
115           6.4          3.2           5.3          2.3  virginica
116           6.5          3.0           5.5          1.8  virginica
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
119           6.0          2.2           5.0          1.5  virginica
120           6.9          3.2           5.7          2.3  virginica
121           5.6          2.8           4.9          2.0  virginica
122           7.7          2.8           6.7          2.0  virginica
123           6.3          2.7           4.9          1.8  virginica
124           6.7          3.3           5.7          2.1  virginica
125           7.2          3.2           6.0          1.8  virginica
126           6.2          2.8           4.8          1.8  virginica
127           6.1          3.0           4.9          1.8  virginica
128           6.4          2.8           5.6          2.1  virginica
129           7.2          3.0           5.8          1.6  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
132           6.4          2.8           5.6          2.2  virginica
133           6.3          2.8           5.1          1.5  virginica
134           6.1          2.6           5.6          1.4  virginica
135           7.7          3.0           6.1          2.3  virginica
136           6.3          3.4           5.6          2.4  virginica
137           6.4          3.1           5.5          1.8  virginica
138           6.0          3.0           4.8          1.8  virginica
139           6.9          3.1           5.4          2.1  virginica
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [13]:
# apply aggregate function
aggregated = grouped.agg({"sepal_length": "mean", "sepal_width": "mean"})
print(aggregated)
print(grouped.mean())
print(grouped.agg({"sepal_length": "mean", "sepal_width": "mean"}))
print(grouped.agg({"sepal_length": "mean", "sepal_width": "mean"}).mean())

            sepal_length  sepal_width
species
setosa             5.006        3.428
versicolor         5.936        2.770
virginica          6.588        2.974
            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.428         1.462        0.246
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026
            sepal_length  sepal_width
species
setosa             5.006        3.428
versicolor         5.936        2.770
virginica          6.588        2.974
sepal_length    5.843333
sepal_width     3.057333
dtype: float64

In [ ]:
# aggregation funciton: Using groupby
df.groupby("species")["petal_length"].mean()

species
setosa        1.462
versicolor    4.260
virginica     5.552
Name: petal_length, dtype: float64

In [15]:
df.groupby("species")["petal_width"].mean()

species
setosa        0.246
versicolor    1.326
virginica     2.026
Name: petal_width, dtype: float64

In [17]:
df.groupby("species").agg({"sepal_length": ["mean",'max','min']})

           sepal_length
                   mean  max  min
species
setosa            5.006  5.8  4.3
versicolor        5.936  7.0  4.9
virginica         6.588  7.9  4.9

In [ ]:
# using pivot table
# pivot table is a way to summarize data and it is a way to transform data
# pivot_table will create a new table with the index as the rows and the columns as the columns

# aggregate function: mean, sum, max, min, count, std, var, median

# synatx of pivot_table: df.pivot_table(values="numeric_column_name",index="column_name",columns="numeric_column_name",aggfunc="function_name")

pivot=df.pivot_table(values="petal_length",index="species",columns="petal_width",aggfunc="mean")
# in the above code, values is the column we want to aggregate, index is the column we want to group by, columns is the column we want to group by, aggfunc is the function we want to use to aggregate
pivot

petal_width,0.1,0.2,0.3,0.4,0.5,0.6,1.0,1.1,1.2,1.3,...,1.6,1.7,1.8,1.9,2.0,2.1,2.2,2.3,2.4,2.5
species,,,,,,,,,,,,,,,,,,,,,
setosa,1.38,1.444828,1.428571,1.571429,1.7,1.6,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
versicolor,NaN,NaN,NaN,NaN,NaN,NaN,3.628571,3.566667,4.24,4.176923,...,4.766667,5.0,4.800000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
virginica,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.800000,4.5,5.381818,5.32,5.55,5.783333,6.033333,5.7,5.433333,5.933333

In [ ]:
# custom aggeration function
def range_fuc(x):
    return x.max() - x.min()

iris = pd.read_csv("iris.csv")
iris.groupby("species").agg({"sepal_length": range_fuc})

            sepal_length
species
setosa               1.5
versicolor           2.1
virginica            3.0

In [24]:
def range_fuc(x):
    return x.max() - x.min()

iris = pd.read_csv("iris.csv")
iris.groupby("species")["sepal_length"].agg(range_fuc)

species
setosa        1.5
versicolor    2.1
virginica     3.0
Name: sepal_length, dtype: float64

In [ ]:
# calculating summary statistics for grouped data
# common statistics:
# count, mean, std, min, 25%, 50%, 75%, max

# synatx iris.groupby("column_name").statistic()

# statistics for species
print(iris.groupby("species").mean())
print(iris.groupby("species").std())
print(iris.groupby("species").min())
print(iris.groupby("species").max())
print(iris.groupby("species").count())
print(iris.groupby("species").median())
print(iris.groupby("species").var())
print(iris.groupby("species").sem())

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.428         1.462        0.246
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026
            sepal_length  sepal_width  petal_length  petal_width
species
setosa          0.352490     0.379064      0.173664     0.105386
versicolor      0.516171     0.313798      0.469911     0.197753
virginica       0.635880     0.322497      0.551895     0.274650
            sepal_length  sepal_width  petal_length  petal_width
species
setosa               4.3          2.3           1.0          0.1
versicolor           4.9          2.0           3.0          1.0
virginica            4.9          2.2           4.5          1.4
            sepal_length  sepal_width  petal_length  petal_width
species
setosa               5.8          4.4           1.9          0.6
versicolor           7.0          3.4           5.1          1.8
virginica            7.9          3.8           6.9          2.5
            sepal_length  sepal_width  petal_length  petal_width
species
setosa                50           50            50           50
versicolor            50           50            50           50
virginica             50           50            50           50
            sepal_length  sepal_width  petal_length  petal_width
species
setosa               5.0          3.4          1.50          0.2
versicolor           5.9          2.8          4.35          1.3
virginica            6.5          3.0          5.55          2.0
            sepal_length  sepal_width  petal_length  petal_width
species
setosa          0.124249     0.143690      0.030159     0.011106
versicolor      0.266433     0.098469      0.220816     0.039106
virginica       0.404343     0.104004      0.304588     0.075433
            sepal_length  sepal_width  petal_length  petal_width
species
setosa          0.049850     0.053608      0.024560     0.014904
versicolor      0.072998     0.044378      0.066455     0.027966
virginica       0.089927     0.045608      0.078050     0.038841

In [ ]:
# statistics for each species
# synatx iris.groupby("column_name")["numeric_column_name"].function()

print(iris.groupby("species")["sepal_length"].mean())
print(iris.groupby("species")["sepal_length"].std())
print(iris.groupby("species")["sepal_length"].min())
print(iris.groupby("species")["sepal_length"].max())
print(iris.groupby("species")["sepal_length"].count())
print(iris.groupby("species")["sepal_length"].median())
print(iris.groupby("species")["sepal_length"].var())
print(iris.groupby("species")["sepal_length"].sem())

species
setosa        5.006
versicolor    5.936
virginica     6.588
Name: sepal_length, dtype: float64
species
setosa        0.352490
versicolor    0.516171
virginica     0.635880
Name: sepal_length, dtype: float64
species
setosa        4.3
versicolor    4.9
virginica     4.9
Name: sepal_length, dtype: float64
species
setosa        5.8
versicolor    7.0
virginica     7.9
Name: sepal_length, dtype: float64
species
setosa        50
versicolor    50
virginica     50
Name: sepal_length, dtype: int64
species
setosa        5.0
versicolor    5.9
virginica     6.5
Name: sepal_length, dtype: float64
species
setosa        0.124249
versicolor    0.266433
virginica     0.404343
Name: sepal_length, dtype: float64
species
setosa        0.049850
versicolor    0.072998
virginica     0.089927
Name: sepal_length, dtype: float64

In [34]:
# multi-aggregation
# syntax iris.groupby('column_name').agg({'column_name': 'aggregation_function'})
iris = pd.read_csv('iris.csv')
iris.groupby('species').agg({'sepal_length': ['mean', 'std'], 'sepal_width': 'mean', 'petal_length': 'mean', 'petal_width': 'mean'})

           sepal_length           sepal_width petal_length petal_width
                   mean       std        mean         mean        mean
species
setosa            5.006  0.352490       3.428        1.462       0.246
versicolor        5.936  0.516171       2.770        4.260       1.326
virginica         6.588  0.635880       2.974        5.552       2.026

In [36]:
# multi-aggregation
# syntax iris.groupby('column_name').agg({'column_name': 'aggregation_function'})
iris = pd.read_csv('iris.csv')
iris.groupby('species').agg({'sepal_length': ['mean', 'std'], 'sepal_width': ['mean', 'std'], 'petal_length': ['mean', 'std'], 'petal_width': ['mean', 'std']})

           sepal_length           sepal_width           petal_length  \
                   mean       std        mean       std         mean
species
setosa            5.006  0.352490       3.428  0.379064        1.462
versicolor        5.936  0.516171       2.770  0.313798        4.260
virginica         6.588  0.635880       2.974  0.322497        5.552

                     petal_width
                 std        mean       std
species
setosa      0.173664       0.246  0.105386
versicolor  0.469911       1.326  0.197753
virginica   0.551895       2.026  0.274650

In [ ]:
# excerise

In [43]:
# group data by a categorical column
iris=pd.read_csv('iris.csv')
print(iris)
grouped=iris.groupby('species').mean()
print(grouped)

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]
            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.428         1.462        0.246
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [44]:
# calculate summary statistics of grouped data
iris = pd.read_csv('iris.csv')
iris.groupby('species').agg({'sepal_length': 'mean', 'sepal_width': 'mean', 'petal_length': 'mean', 'petal_width': 'mean'})

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.428         1.462        0.246
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [47]:
pip install matplotlib
pip install seaborn
pip install plotly
pip install missingno
pip install os

SyntaxError: invalid syntax (1389845640.py, line 1)

In [45]:
# create a dataset of sales data and group it by month and calculate the total sales for each month
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import warnings
warnings.filterwarnings('ignore')

# create a dataset of sales data and group it by month and calculate the total sales for each month
sales_data = pd.read_csv('sales_data.csv')
sales_data['month'] = pd.to_datetime(sales_data['date']).dt.month
sales_data.groupby('month').sum()
sales_data.groupby('month').sum().plot(kind='bar')

ModuleNotFoundError: No module named 'matplotlib'

In [52]:
# create a dataset of sales data and group it by region or product type

import pandas as pd
import numpy as np
sales_data = [
    {"id": 1, "product": "Laptop", "region": "North", "amount": 1200},
    {"id": 2, "product": "Mouse", "region": "South", "amount": 25},
    {"id": 3, "product": "Keyboard", "region": "North", "amount": 75},
    {"id": 4, "product": "Laptop", "region": "East", "amount": 1300},
    {"id": 5, "product": "Mouse", "region": "North", "amount": 20},
    {"id": 6, "product": "Monitor", "region": "West", "amount": 300},
    {"id": 7, "product": "Laptop", "region": "South", "amount": 1150},
    {"id": 8, "product": "Keyboard", "region": "West", "amount": 80},
    {"id": 9, "product": "Monitor", "region": "North", "amount": 320},
    {"id": 10, "product": "Mouse", "region": "East", "amount": 30}
]
sales_df = pd.DataFrame(sales_data)
sales_by_region=sales_df.groupby('region').agg({'amount': 'sum'})
sales_by_product=sales_df.groupby('product').agg({'amount': 'sum'})
print(sales_by_region)
print(sales_by_product)

        amount
region
East      1330
North     1615
South     1175
West       380
          amount
product
Keyboard     155
Laptop      3650
Monitor      620
Mouse         75

In [54]:
# use pivot_table to calculate the total sales by region and product
sales_df.pivot_table(index='region', columns='product', values='amount', aggfunc='sum')

product  Keyboard  Laptop  Monitor  Mouse
region
East          NaN  1300.0      NaN   30.0
North        75.0  1200.0    320.0   20.0
South         NaN  1150.0      NaN   25.0
West         80.0     NaN    300.0    NaN

In [58]:
# create a custom aggregation function to calculate the variance of each group

sales_data = [
    {"id": 1, "product": "Laptop", "region": "North", "amount": 1200},
    {"id": 2, "product": "Mouse", "region": "South", "amount": 25},
    {"id": 3, "product": "Keyboard", "region": "North", "amount": 75},
    {"id": 4, "product": "Laptop", "region": "East", "amount": 1300},
    {"id": 5, "product": "Mouse", "region": "North", "amount": 20},
    {"id": 6, "product": "Monitor", "region": "West", "amount": 300},
    {"id": 7, "product": "Laptop", "region": "South", "amount": 1150},
    {"id": 8, "product": "Keyboard", "region": "West", "amount": 80},
    {"id": 9, "product": "Monitor", "region": "North", "amount": 320},
    {"id": 10, "product": "Mouse", "region": "East", "amount": 30}
]
sales_df = pd.DataFrame(sales_data)

def variance(x):
    return np.var(x)

sales_df.groupby('region').agg({'amount': variance})

             amount
region
East    403225.0000
North   224092.1875
South   316406.2500
West     12100.0000